<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Goals</AssemblyName>
    <RootNamespace>Goals.Windows</RootNamespace>
    <StartupObject>Goals.Windows.Program</StartupObject>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\Goals.ico</ApplicationIcon>
    <PublishSingleFile>false</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishReadyToRun>true</PublishReadyToRun>
    <DebugType>embedded</DebugType>
    <Version>1.1.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\AppIcon04.png" />
    <Resource Include="Assets\Goals.ico" />
    <Content Include="THIRD-PARTY-NOTICES.txt" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Models\opus-mt-ja-zh\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MDict.Csharp" Version="0.1.2" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.2" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.29.0" />
    <PackageReference Include="Velopack" Version="1.2.0" />
  </ItemGroup>
</Project>
